### ISSUE TITLE
Allow !!js/function in all return properties

### ISSUE THREAD

**Issue by inkhsutesou** [RonaldJerez/simpler-mocks#1]
In a project, we wanted to return a random status between 500 / 204.

We should be allowed to place JavaScript wherever there is a possible response for flexibility.

Thank you

**Comment by RonaldJerez** [comment]
Having a function for responses is something I have tried, and will likely implement in the future. I ran into some issues passing certain data from koa to said functions though, so I didn't want to half implement it. 

In the meantime, for the scenario you described the following should work using chance's pickone method:

`:status: !random pickone 204|500`
